### ISSUE TITLE
Link in Readme is dead

### ISSUE THREAD

**Issue by DeqingSun** [heretic1993/autoCalibration#1]
Hi, the link in Readme is dead, is there a new link? I'm interested in reading it.

**Comment by heretic1993** [comment]
你好，请参考：
https://blog.csdn.net/heretic1993/article/details/82116742/

谢谢

**Comment by DeqingSun** [comment]
谢谢，里面的图片开了天窗，视频也载入不了。我最近在尝试做标定，很想看看相关资料。

**Comment by heretic1993** [comment]
For reference,

![hand-eye-cali-realsense](https://user-images.githubusercontent.com/8786669/89241853-07db1900-d5ce-11ea-8391-7eb5c4ac7144.png)
![hand-eye-cali-thumbnails](https://user-images.githubusercontent.com/8786669/89241854-0873af80-d5ce-11ea-85d4-f2772a399b60.jpg)
![hand-eye-cali-aruco](https://user-images.githubusercontent.com/8786669/89241847-04479200-d5ce-11ea-8de7-ba87675de466.jpg)
<img width="575" alt="hand-eye-cali-cord" src="https://user-images.githubusercontent.com/8786669/89241849-04e02880-d5ce-11ea-8fe4-16aa5b0ec9bf.png">
![hand-eye-cali-env](https://user-images.githubusercontent.com/8786669/89241850-0578bf00-d5ce-11ea-9b37-c5be5e50c10d.JPG)

**Comment by heretic1993** [comment]
> 谢谢，里面的图片开了天窗，视频也载入不了。我最近在尝试做标定，很想看看相关资料。

视频链接：
https://youtu.be/I7UYUe6PVnY

**Comment by DeqingSun** [comment]
非常感谢！
